// <auto-generated />
using System;
using E_Migrant.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Migrant.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211128031122_bd1mp")]
    partial class bd1mp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Alimentacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Alimentacion");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.AlojamientoPermanent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AlojamientoPermanent");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.AlojamientoTemp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AlojamientoTemp");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.AyudaLegal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AyudaLegal");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Educacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Educacion");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Empleo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Empleo");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.GrupoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("tipoPersona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GrupoPersonas");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Migrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AlojoPermanenteid")
                        .HasColumnType("int");

                    b.Property<int?>("AlojoTemporalid")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AyudaLegalid")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Educacionid")
                        .HasColumnType("int");

                    b.Property<int?>("Empleoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("FNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("alimentacionid")
                        .HasColumnType("int");

                    b.Property<string>("clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("saludid")
                        .HasColumnType("int");

                    b.Property<int>("situacionLaborlal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlojoPermanenteid");

                    b.HasIndex("AlojoTemporalid");

                    b.HasIndex("AyudaLegalid");

                    b.HasIndex("Educacionid");

                    b.HasIndex("Empleoid");

                    b.HasIndex("alimentacionid");

                    b.HasIndex("saludid");

                    b.ToTable("Migrantes");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Salud", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Salud");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Migrante", b =>
                {
                    b.HasOne("E_Migrant.App.Dominio.Entidades.AlojamientoPermanent", "AlojoPermanente")
                        .WithMany()
                        .HasForeignKey("AlojoPermanenteid");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.AlojamientoTemp", "AlojoTemporal")
                        .WithMany()
                        .HasForeignKey("AlojoTemporalid");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.AyudaLegal", "AyudaLegal")
                        .WithMany()
                        .HasForeignKey("AyudaLegalid");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.Educacion", "Educacion")
                        .WithMany()
                        .HasForeignKey("Educacionid");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.Empleo", "Empleo")
                        .WithMany()
                        .HasForeignKey("Empleoid");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.Alimentacion", "alimentacion")
                        .WithMany()
                        .HasForeignKey("alimentacionid");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.Salud", "salud")
                        .WithMany()
                        .HasForeignKey("saludid");

                    b.Navigation("alimentacion");

                    b.Navigation("AlojoPermanente");

                    b.Navigation("AlojoTemporal");

                    b.Navigation("AyudaLegal");

                    b.Navigation("Educacion");

                    b.Navigation("Empleo");

                    b.Navigation("salud");
                });
#pragma warning restore 612, 618
        }
    }
}
